# Generated by Django 5.1.1 on 2024-09-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
