# Generated by Django 5.1.1 on 2024-10-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0003_alter_deck_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='decks',
        ),
        migrations.AddField(
            model_name='deck',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='decks', to='mtg_decks.tag'),
        ),
    ]
