# Generated by Django 5.1.1 on 2024-09-23 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_decks', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_abbreviation', models.CharField(max_length=10)),
                ('tix', models.DecimalField(decimal_places=3, max_digits=6)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='best_price', to='mtg_decks.card')),
            ],
        ),
    ]
